config/routes.rb
InterviewScheduler::Application.routes.draw do
  root :to => "applicants#index"

  resources :applicants

end

app/models/applicant.rb
class Applicant < ActiveRecord::Base
  attr_accessible :email, :name

  validates :name, :presence => true
end

app/controllers/applicants_controller.rb
class ApplicantsController < ApplicationController

  def index
    @applicants = Applicant.all
  end

  def new
    @applicant = Applicant.new
  end

  def create
    @applicant = Applicant.new(params[:applicant])
    if @applicant.save
      flash[:notice] = "Applicant has been created."
      redirect_to @applicant
    else
      flash[:alert] = "Applicant has not been created."
      render :action => "new"
    end
  end

  def show
    @applicant = Applicant.find(params[:id])
  end

  def destroy
    @applicant = Applicant.find(params[:id])
    @applicant.destroy
    flash[:notice] = "Applicant has been deleted."
    redirect_to applicants_path
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/helpers/applicants_helper.rb
module ApplicantsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/applicants/index.html.erb
<h2>Applicants</h2>
<ul>
  <% @applicants.each do |applicant| %>
    <li><%= link_to applicant.name, applicant %></li>
  <% end %>
</ul>

<%= link_to "New Applicant", new_applicant_path %>

app/views/applicants/new.html.erb
<h2>New Applicant</h2>

<%= form_for(@applicant) do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.label :email %>
    <%= f.text_field :email %>
  </p>
  <%= f.submit %>
<% end %>

app/views/applicants/show.html.erb
<h2><%= @applicant.name %></h2>
<%= link_to "Delete Applicant", applicant_path(@applicant),
    :method => :delete,
    :confirm => "Are you sure you want to delete this applicant?" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>InterviewScheduler</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<% flash.each do |key, value| %>
  <div class="flash" id="<%= key %>"><%= value %></div>
<% end %>

<%= yield %>

</body>
</html>